### ISSUE TITLE
Funland v0.0.1.2 - ItemData.cs Line 171 

### ISSUE THREAD

**Issue by Noahers** [jeffman/MOTHER-3-Funland#1]
Hello Jeffman!

Thanks a lot for the awesome tool!

The item data does not save correctly in v0.0.1.2. I am using the fan translation 1.1 rom.

Line 171 has an offset of 7 for the HP, but when reading the data, the HP starts at an offset of 3 (line 93).

I recompiled after changing the offset on line 171 to 3 and the items seem to be saving fine for me.

I see that the offset was changed to fix a white-space issue, so maybe by changing the offset back to 3 I am creating another issue, but I just wanted to call it to your attention!

Thanks!
- Noah

**Comment by jeffman** [comment]
You're right, thanks for the heads up! I've committed the fix.
